 declare
    type array_t is varray(24) of varchar2(100);
    array array_t := array_t(
       'alter table clinic       drop constraint clinic_fk2',
       'alter table clinic_users drop constraint clinic_users_fk0',
       'alter table clinic_users drop constraint clinic_users_fk1',
       'alter table user_bills   drop constraint user_bills_fk0',
       'alter table user_bills   drop constraint user_bills_fk1',

       'DROP table users',
       'DROP table city',
       'DROP table clinic',
       'DROP table bill',
       'DROP table clinic_users',
       'DROP table user_bills',

       'DROP procedure digit_magic',
       'DROP procedure bill_zero',
       'DROP procedure discount_bill',
       'DROP procedure p_boolean',
       'DROP procedure p_number',
       'DROP procedure p_int',
       'DROP procedure p_float',
       'DROP procedure p_double',
       'DROP procedure p_varchar',
       'DROP procedure p_date',
       'DROP procedure p_timestamp',
       'DROP procedure p_timestamptz',
       'DROP procedure p_raw'
    );
begin
   for i in 1..array.count loop
       begin
          execute immediate array(i);
       exception
           when others then
              if sqlcode != -4043 and
                 sqlcode != -942  and
                 sqlcode != -2443 then raise; end if;
       end;
   end loop;
   execute immediate '
        create table users (
              id number(19) generated by default on null as identity,
              name varchar(100) not null,
              info varchar(200),
              -- sex enum_user_sex,
              constraint users_pk primary key (id)
          )';
   execute immediate '
       create table clinic (
              id number(19) primary key,
              name varchar(100) not null,
              city_id number(19) not null
          )';

   execute immediate '
          create table city (
                 id number(19) primary key,
                 name varchar(50) not null
             )';
   execute immediate '
       create table bill (
              id number(19) primary key,
              amount number(15,2) not null,
              discount number(15,2),
              "date" timestamp with time zone not null
          )';
   execute immediate '
       create table clinic_users (
              clinic_id number(19) not null,
              user_id number(19) not null
          )';
   execute immediate '
       create table user_bills (
              user_id number(19) not null,
              bill_id number(19) not null
          )';

   execute immediate 'alter table clinic       add constraint clinic_fk2       foreign key (city_id)   references city(id)';
   execute immediate 'alter table clinic_users add constraint clinic_users_fk0 foreign key (clinic_id) references clinic(id)';
   execute immediate 'alter table clinic_users add constraint clinic_users_fk1 foreign key (user_id)   references users(id)';
   execute immediate 'alter table user_bills   add constraint user_bills_fk0   foreign key (user_id)   references users(id)';
   execute immediate 'alter table user_bills   add constraint user_bills_fk1   foreign key (bill_id)   references bill(id)';
   execute immediate '
       create procedure digit_magic(
              x IN int, y IN OUT int, z OUT int
          ) is begin
              y := y + x;
              z := y + x;
          end;';
   execute immediate '
          create procedure bill_zero
          is begin
              update bill set amount = 0;
          end;';

   execute immediate '
          create procedure discount_bill(datedisc IN timestamp)
          is begin
              update bill set discount = amount * 0.1 where "date" = datedisc;
          end;';

   execute immediate '
          create procedure p_boolean(x IN boolean, y OUT boolean)
          is begin y := x; end;';
   execute immediate '
          create procedure p_number(x IN number, y OUT number)
          is begin y := x; end;';
   execute immediate '
          create procedure p_int(x IN int, y OUT int)
          is begin y := x; end;';
   execute immediate '
          create procedure p_float(x IN binary_float, y OUT binary_float)
          is begin y := x; end;';
   execute immediate '
          create procedure p_double(x IN binary_double, y OUT binary_double)
          is begin y := x; end;';
   execute immediate '
          create procedure p_varchar(x IN varchar, y OUT varchar)
          is begin y := x; end;';
   execute immediate '
          create procedure p_date(x IN date, y OUT date)
          is begin y := x; end;';
   execute immediate '
          create procedure p_timestamp(x IN timestamp, y OUT timestamp)
          is begin y := x; end;';
   execute immediate '
          create procedure p_timestamptz(x IN timestamp with time zone, y OUT timestamp with time zone)
          is begin y := x; end;';
   execute immediate '
          create procedure p_raw(x IN raw, y OUT raw)
          is begin y := x; end;';
end;

