declare
    type array_t is varray(16) of varchar2(100);
    array array_t := array_t(
       'alter table clinic       drop constraint clinic_fk2',
       'alter table clinic_users drop constraint clinic_users_fk0',
       'alter table clinic_users drop constraint clinic_users_fk1',
       'alter table user_bills   drop constraint user_bills_fk0',
       'alter table user_bills   drop constraint user_bills_fk1',

       'DROP table users',
       'DROP table city',
       'DROP table clinic',
       'DROP table bill',
       'DROP table clinic_users',
       'DROP table user_bills',
       'DROP table all_default_data_types',

       'DROP procedure digit_magic',
       'DROP procedure bill_zero',
       'DROP procedure discount_bill',
       'DROP procedure test_types_procedure'
    );
begin
   for i in 1..array.count loop
       begin
          execute immediate array(i);
       exception
           when others then
              if sqlcode != -4043 and
                 sqlcode != -942  and
                 sqlcode != -2443 then raise; end if;
       end;
   end loop;
   execute immediate '
        create table users (
              id number(19) generated by default on null as identity,
              name varchar(100) not null,
              info varchar(200),
              -- sex enum_user_sex,
              constraint users_pk primary key (id)
          )';
   execute immediate '
       create table clinic (
              id number(19) primary key,
              name varchar(100) not null,
              city_id number(19) not null
          )';

   execute immediate '
          create table city (
                 id number(19) primary key,
                 name varchar(50) not null
             )';
   execute immediate '
       create table bill (
              id number(19) primary key,
              amount number(15,2) not null,
              discount number(15,2),
              "date" timestamp with time zone not null
          )';
   execute immediate '
       create table clinic_users (
              clinic_id number(19) not null,
              user_id number(19) not null
          )';
   execute immediate '
       create table user_bills (
              user_id number(19) not null,
              bill_id number(19) not null
          )';
   execute immediate '
          create table all_default_data_types(
              bigdecimal_type number(15,3) not null,
              bigdecimal_type_null number(15,3),
              boolean_type      char(1) not null,
              boolean_type_null char(1),
              date_type date not null,
              date_type_null date,
              integer_type number(10) not null,
              integer_type_null number(10),
              long_type number(19) not null,
              long_type_null number(19),
              string_type varchar(200) not null,
              string_type_null varchar(200),
              short_type number(5) not null,
              short_type_null number(5),
              timestamp_type timestamp not null,
              timestamp_type_null timestamp
          )';

   execute immediate 'alter table clinic       add constraint clinic_fk2       foreign key (city_id)   references city(id)';
   execute immediate 'alter table clinic_users add constraint clinic_users_fk0 foreign key (clinic_id) references clinic(id)';
   execute immediate 'alter table clinic_users add constraint clinic_users_fk1 foreign key (user_id)   references users(id)';
   execute immediate 'alter table user_bills   add constraint user_bills_fk0   foreign key (user_id)   references users(id)';
   execute immediate 'alter table user_bills   add constraint user_bills_fk1   foreign key (bill_id)   references bill(id)';
   execute immediate '
       create procedure digit_magic(
              x IN int, y IN OUT int, z OUT int
          ) is begin
              y := y + x;
              z := y + x;
          end;';
   execute immediate '
          create procedure bill_zero
          is begin
              update bill set amount = 0;
          end;';

   execute immediate '
          create procedure discount_bill(datedisc IN timestamp)
          is begin
              update bill set discount = amount * 0.1 where "date" = datedisc;
          end;';

   execute immediate '
       create or replace procedure test_types_procedure (

           bigdecimal_type      IN OUT number,
           bigdecimal_type_null OUT    number,

           boolean_type         in out boolean,
           boolean_type_null    out    boolean,

           date_type            in out  date,
           date_type_null       out     date,

           integer_type         in out integer,
           integer_type_null    out    integer,

           long_type            in out number,
           long_type_null       out    number,

           string_type          in out varchar,
           string_type_null     out    varchar,

           short_type          in out smallint,
           short_type_null     out   smallint,

           byte_type           in out number,
           byte_type_null      out    number,

           timestamp_type      in out timestamp,
           timestamp_type_null out    timestamp

       ) is begin
           null;
       end;
   ';
end;

